apiVersion: v1
kind: Service
metadata:
  name: {{ template "hollywood.fullname" . }}-actors
  labels:
    app: {{ template "hollywood.name" . }}-actors
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.actors.service.type }}
  ports:
    - port: {{ .Values.actors.service.externalPort }}
      targetPort: {{ .Values.actors.service.internalPort }}
      protocol: TCP
      name: {{ .Values.actors.service.name }}
  selector:
    app: {{ template "hollywood.name" . }}-actors
    release: {{ .Release.Name }}
