apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hollywood.fullname" . }}-images
  labels:
    app: {{ template "hollywood.name" . }}-images
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: |-
    spring:
      datasource:
        url: jdbc:mysql://{{ .Release.Name }}-mysql:3306/mysql
        username: root
        password: ${MYSQL_ROOT_PASSWORD}
        driverClassName: com.mysql.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"
      zipkin:
        baseUrl: http://{{ template "hollywood.fullname" . }}-zipkin:{{ .Values.zipkin.service.externalPort }}
