apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hollywood.fullname" . }}-prometheus
  labels:
    app: {{ template "hollywood.name" . }}
    component: prometheus
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      static_configs: 
      - targets: ['localhost:9090']
    - job_name: 'zipkin'
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      metrics_path: '/prometheus'
      static_configs:
      - targets: ['{{ template "hollywood.fullname" . }}-zipkin:{{ .Values.zipkin.service.externalPort }}']
    - job_name: 'hollywood'
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      metrics_path: '/application/prometheus'
      static_configs:
      - targets: ['{{ template "hollywood.fullname" . }}-actors:{{ .Values.actors.service.externalPort }}','{{ template "hollywood.fullname" . }}-images:{{ .Values.images.service.externalPort }}','{{ template "hollywood.fullname" . }}-gateway:{{ .Values.gateway.service.externalPort }}']
