apiVersion: v1
kind: ConfigMap
metadata:
  name: price-service-configmap
  namespace: KUBERNETES_NAMESPACE_VAR
data:
  MONGO_CONNECTION_URI: mongodb://cdbcusppexrwdi4:WIr11KSrFASQyrLaELTuIJppmuSYmLC1Ig9tnMcxTOhiKzZV3eCgNTy0VrlSlEcG0893BXDvbiI3AMuibpKqGw==@cdbcusppexrwdi4.documents.azure.com:10255/ipimipdb?ssl=true&replicaSet=globaldb
  PORT: "8080"
  KAFKA_BROKERS: 10.23.126.13:9094,10.23.126.11:9094,10.23.126.15:9094
  KAFKA_RATE_TOPIC: ipimip-fx-rate
  SPRING_LOG_LEVEL: INFO
  IKEA_LOG_LEVEL: INFO