apiVersion: v1
kind: ConfigMap
metadata:
  name: price-service-configmap
  namespace: KUBERNETES_NAMESPACE_VAR
data:
  MONGO_CONNECTION_URI: mongodb://cdbwedevgupuy7:LgojPg9QbDq7Tt2ZiqkJC8EeXuUDZVE8Fz4tR975rwgwTk4HUMGLJFHhquhNfd54YKhGZkwWRYTOg34iJJoY7w==@cdbwedevgupuy7.documents.azure.com:10255/ipimipdb?ssl=true&replicaSet=globaldb
  PORT: "8080"
  KAFKA_BROKERS: 10.18.126.8:9094
  KAFKA_RATE_TOPIC: ipimip-fx-rate
  SPRING_LOG_LEVEL: INFO
  IKEA_LOG_LEVEL: DEBUG