apiVersion: v1
kind: ConfigMap
metadata:
  name: SERVICE_NAME_VAR-configmap
  namespace: KUBERNETES_NAMESPACE_VAR
data:
  KAFKA_TOPICS: ipimip-fx-rate
  KAFKA_BROKERS: 10.13.126.6:9094,10.13.126.12:9094,10.13.126.16:9094