apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
data:
  config.yaml: |
    server:
      port: 20001
    external_services:
      jaeger:
        url: http://dev.trace.westeurope.hip.red.cdtapps.com
      grafana:
        url: http://grafana.istio-system:3000
        username: admin
        password: admin4ipimIP
      prometheus_service_url: http://prometheus:9090