---
apiVersion: v1
kind: Service
metadata:
  name: price-service
  labels:
    app: price-service
    version: v1
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http-priceservice
  selector:
    app: price-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: price-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-service
  template:
    metadata:
      labels:
        app: price-service
        version: v1
    spec:
      containers:
      - name: price-service
        image: acrwedevgupuy7.azurecr.io/apimgt/price-service:1.0.167-SNAPSHOT
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: certs
          mountPath: "/etc/certs"
          readOnly: true
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
        #livenessProbe:
        #  httpGet:
        #    path: /actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 30
        #  periodSeconds: 120
        #  successThreshold: 1
        #readinessProbe:
        #  httpGet:
        #    path: /actuator/info
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 10
        #  periodSeconds: 5
        #  successThreshold: 3
        env:
        - name: MONGO_CONNECTION_URI
          valueFrom:
            secretKeyRef:
              name: dev-mongo-db
              key: MONGO_CONNECTION_URI
        - name: MONGO_DB_HOST
          valueFrom:
            secretKeyRef:
              name: dev-mongo-db
              key: MONGO_DB_HOST
        - name: MONGO_DB_PORT
          valueFrom:
            secretKeyRef:
              name: dev-mongo-db
              key: MONGO_DB_PORT
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: dev-mongo-db
              key: MONGO_DATABASE
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: dev-mongo-db
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-mongo-db
              key: MONGO_PASSWORD
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-price-service
              key: PORT
        - name: SPRING_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: common-configmap
              key: DEV_SPRING_LOG_LEVEL
        - name: IKEA_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: common-configmap
              key: DEV_IKEA_LOG_LEVEL
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: configmap-price-service
              key: KAFKA_BROKERS
        - name: KAFKA_RATE_TOPIC
          valueFrom:
            configMapKeyRef:
              name: configmap-price-service
              key: KAFKA_RATE_TOPIC
      volumes:
      - name: certs
        secret:
          secretName: istio.default